// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkuilhkeznitxmyoevjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rdWlsaGtlem5pdHhteW9ldmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjkxNDMsImV4cCI6MjA2NzU0NTE0M30.j3FVcyrfJwuevyNlR0VrZThnz_LM-U9Fz0OXK_of7kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});